server:
  address: 192.168.1.33
  port: 9000
  error:
    include-message: always
    include-binding-errors: always
    include-exception: false

# Подключение к БД
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_test_authorization?useSSL=false&useJDBCCompliantTimezoneShift=true&useUnicode=true&characterEncoding=UTF-8&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB  # Threshold after which files are written to disk
      max-file-size: 20MB # Max file size
      max-request-size: 20MB # Max Request Size


logging:
  level:
   root: INFO