server:
  address: 192.168.1.33
  port: 9000

# Подключение к БД
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_test_authorization?useSSL=false&useJDBCCompliantTimezoneShift=true&useUnicode=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

